apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-virtual-host-ingress-blue
spec:
  rules:
  - host: ngnix.opentlc-blue.example.com
    http:
      paths:
      - backend:
          serviceName: blue-nginx-service
          servicePort: 8080
